#!/bin/bash

sudo docker build -t capstone .

if [ $1 > -1 ] && [ $1 < 65536 ]
then
    sudo docker run -p $va:$val -it --privileged capstone 

else
    sudo docker run -p 8080:8080 -it --privileged capstone

fi
